In [1]:
from keras import Sequential
from keras.layers import Dense, SimpleRNN

In [2]:
model = Sequential()

model.add(SimpleRNN(3, input_shape=(4,5)))
model.add(Dense(1, activation = 'sigmoid'))

model.summary()

/usr/local/lib/python3.10/dist-packages/keras/src/layers/rnn/rnn.py:204: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ simple_rnn (SimpleRNN)               │ (None, 3)                   │              27 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense (Dense)                        │ (None, 1)                   │               4 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 31 (124.00 B)

 Trainable params: 31 (124.00 B)

 Non-trainable params: 0 (0.00 B)

In [3]:
print(model.get_weights()[0].shape)
model.get_weights()[0]

(5, 3)


array([[ 0.7222958 , -0.39231452,  0.8102338 ],
       [-0.22253048,  0.51329476, -0.11307728],
       [ 0.6616803 , -0.03424352, -0.5571724 ],
       [-0.75588584, -0.19022644, -0.36317575],
       [-0.33432722,  0.39289182, -0.86212236]], dtype=float32)

In [4]:
print(model.get_weights()[1].shape)
model.get_weights()[1]

(3, 3)


array([[-0.92152417,  0.19919482, -0.33333844],
       [ 0.27871045, -0.25844836, -0.92494595],
       [ 0.27039522,  0.945265  , -0.18264875]], dtype=float32)

In [5]:
print(model.get_weights()[2].shape)
model.get_weights()[2]

(3,)


array([0., 0., 0.], dtype=float32)

In [6]:
print(model.get_weights()[4].shape)
model.get_weights()[4]

(1,)


array([0.], dtype=float32)

In [7]:
import torch
from torch import nn

In [8]:
try:
  from torchinfo import summary
except:
  !pip install -q torchinfo
  from torchinfo import summary

In [9]:
class SimpleRNN(nn.Module):
    def __init__(self, n_inputs, n_neurons):
        super().__init__()
        self.rnn = nn.RNN(n_inputs, n_neurons, batch_first=False)
        self.fc = nn.Linear(n_neurons, 1)
        self.sigmoid = nn.Sigmoid()

    def forward(self, x):
        out, _ = self.rnn(x)
        out = self.fc(out[-1, :, :])
        out = self.sigmoid(out)
        return out

model1 = SimpleRNN(5, 3)

# Create a sample input
input_seq = torch.randn(4, 1, 5)

summary(model1, input_size=(4, 1, 5))

Layer (type:depth-idx)                   Output Shape              Param #
SimpleRNN                                [1, 1]                    --
├─RNN: 1-1                               [4, 1, 3]                 30
├─Linear: 1-2                            [1, 1]                    4
├─Sigmoid: 1-3                           [1, 1]                    --
Total params: 34
Trainable params: 34
Non-trainable params: 0
Total mult-adds (M): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

In [10]:
# Get weights
for name, param in model1.named_parameters():
    print(f"Layer: {name}, Shape: {param.shape}")
    print(param)
    print("-" * 20)

output = model1(input_seq)
print("Output Shape:", output.shape)
print("Output:", output)

Layer: rnn.weight_ih_l0, Shape: torch.Size([3, 5])
Parameter containing:
tensor([[ 0.4702, -0.2662, -0.1614,  0.3212,  0.5687],
        [ 0.1928, -0.2423, -0.2307,  0.3806,  0.3177],
        [ 0.4798,  0.3733,  0.3049, -0.0479,  0.1697]], requires_grad=True)
--------------------
Layer: rnn.weight_hh_l0, Shape: torch.Size([3, 3])
Parameter containing:
tensor([[-0.4786, -0.5299, -0.0424],
        [ 0.3167,  0.1553,  0.2257],
        [ 0.2022, -0.2553, -0.3498]], requires_grad=True)
--------------------
Layer: rnn.bias_ih_l0, Shape: torch.Size([3])
Parameter containing:
tensor([-0.5165,  0.1109,  0.0217], requires_grad=True)
--------------------
Layer: rnn.bias_hh_l0, Shape: torch.Size([3])
Parameter containing:
tensor([ 0.3422,  0.4552, -0.3813], requires_grad=True)
--------------------
Layer: fc.weight, Shape: torch.Size([1, 3])
Parameter containing:
tensor([[-0.3777, -0.1570, -0.4224]], requires_grad=True)
--------------------
Layer: fc.bias, Shape: torch.Size([1])
Parameter containing

In [13]:
class SimpleLSTM(nn.Module):
    def __init__(self, n_inputs, n_neurons):
        super().__init__()
        self.lstm = nn.LSTM(n_inputs, n_neurons, batch_first=False)
        self.fc = nn.Linear(n_neurons, 1)
        self.sigmoid = nn.Sigmoid()

    def forward(self, x):
        out, _ = self.lstm(x)
        out = self.fc(out[-1, :, :])
        out = self.sigmoid(out)
        return out


model2 = SimpleLSTM(5, 3)

# Create a sample input
input_seq = torch.randn(4, 1, 5)

summary(model2, input_size=(4, 1, 5))

Layer (type:depth-idx)                   Output Shape              Param #
SimpleLSTM                               [1, 1]                    --
├─LSTM: 1-1                              [4, 1, 3]                 120
├─Linear: 1-2                            [1, 1]                    4
├─Sigmoid: 1-3                           [1, 1]                    --
Total params: 124
Trainable params: 124
Non-trainable params: 0
Total mult-adds (M): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

In [14]:
# Get weights
for name, param in model2.named_parameters():
    print(f"Layer: {name}, Shape: {param.shape}")
    print(param)
    print("-" * 20)

output = model2(input_seq)
print("Output Shape:", output.shape)
print("Output:", output)

Layer: lstm.weight_ih_l0, Shape: torch.Size([12, 5])
Parameter containing:
tensor([[-0.1099, -0.0776, -0.0163,  0.3198,  0.4249],
        [-0.0601,  0.4510, -0.5650,  0.2973, -0.5478],
        [ 0.5100, -0.0415,  0.5473,  0.2193, -0.3519],
        [ 0.4817, -0.0470,  0.0167,  0.2843,  0.4659],
        [-0.1825, -0.4112,  0.2079,  0.2790, -0.3474],
        [-0.4749, -0.2246, -0.5095, -0.5080,  0.0958],
        [-0.0195,  0.3965, -0.1218,  0.4515, -0.4201],
        [ 0.3152,  0.1049,  0.4333,  0.3988,  0.4020],
        [-0.2913,  0.4573,  0.1957,  0.5670,  0.2506],
        [ 0.3847, -0.1539, -0.0893, -0.3664, -0.0995],
        [-0.5221,  0.2963, -0.3976, -0.3920,  0.4182],
        [ 0.1329,  0.1781, -0.5018,  0.0695, -0.4020]], requires_grad=True)
--------------------
Layer: lstm.weight_hh_l0, Shape: torch.Size([12, 3])
Parameter containing:
tensor([[ 0.2071,  0.0940,  0.5196],
        [ 0.5515,  0.2790,  0.2239],
        [ 0.4291, -0.3637, -0.0406],
        [ 0.3342, -0.4909,  0.1363],
