In [1]:
import numpy as np

docs = ['go nepal',
		'india nepal',
		'hip hip hurray',
		'jeetega bhai jeetega nepal jeetega',
		'jai nepal',
		'kohli kohli',
		'sachin sachin',
		'dhoni dhoni',
		'tmkoc ji ki jai',
		'aayo gorkhali']

In [2]:
from tensorflow.keras.preprocessing.text import Tokenizer
tokenizer = Tokenizer()

In [3]:
tokenizer.fit_on_texts(docs)

In [4]:
len(tokenizer.word_index)

16

In [5]:
sequences = tokenizer.texts_to_sequences(docs)
sequences

[[8, 1],
 [9, 1],
 [3, 3, 10],
 [2, 11, 2, 1, 2],
 [4, 1],
 [5, 5],
 [6, 6],
 [7, 7],
 [12, 13, 14, 4],
 [15, 16]]

In [6]:
from tensorflow.keras.utils import pad_sequences
sequences = pad_sequences(sequences,padding='post')
sequences

array([[ 8,  1,  0,  0,  0],
       [ 9,  1,  0,  0,  0],
       [ 3,  3, 10,  0,  0],
       [ 2, 11,  2,  1,  2],
       [ 4,  1,  0,  0,  0],
       [ 5,  5,  0,  0,  0],
       [ 6,  6,  0,  0,  0],
       [ 7,  7,  0,  0,  0],
       [12, 13, 14,  4,  0],
       [15, 16,  0,  0,  0]], dtype=int32)

In [20]:
model = Sequential()
model.add(Embedding(17,output_dim=2,input_length=5))

model.summary()

/usr/local/lib/python3.10/dist-packages/keras/src/layers/core/embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


Model: "sequential_4"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ embedding_4 (Embedding)              │ ?                           │     0 (unbuilt) │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [10]:
model.compile('adam','accuracy')

In [11]:
pred = model.predict(sequences)
print(pred)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 166ms/step
[[[-0.0098619  -0.02587336]
  [ 0.00694263  0.04830318]
  [-0.04462224  0.0236344 ]
  [-0.04462224  0.0236344 ]
  [-0.04462224  0.0236344 ]]

 [[ 0.0145773   0.02289779]
  [ 0.00694263  0.04830318]
  [-0.04462224  0.0236344 ]
  [-0.04462224  0.0236344 ]
  [-0.04462224  0.0236344 ]]

 [[-0.01589007  0.02584029]
  [-0.01589007  0.02584029]
  [ 0.04984627  0.0394161 ]
  [-0.04462224  0.0236344 ]
  [-0.04462224  0.0236344 ]]

 [[-0.00551267 -0.026732  ]
  [ 0.01054569  0.02550519]
  [-0.00551267 -0.026732  ]
  [ 0.00694263  0.04830318]
  [-0.00551267 -0.026732  ]]

 [[ 0.04760826  0.01159477]
  [ 0.00694263  0.04830318]
  [-0.04462224  0.0236344 ]
  [-0.04462224  0.0236344 ]
  [-0.04462224  0.0236344 ]]

 [[-0.02985098  0.00390296]
  [-0.02985098  0.00390296]
  [-0.04462224  0.0236344 ]
  [-0.04462224  0.0236344 ]
  [-0.04462224  0.0236344 ]]

 [[-0.04546175  0.04349736]
  [-0.04546175  0.04349736]
  [-0.04462224  0.0236344 ]
  [-0.04462224  0.0236344

In [19]:
from tensorflow.keras.datasets import imdb
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense,SimpleRNN,Embedding,Flatten

In [32]:
(X_train,y_train),(X_test,y_test) = imdb.load_data(num_words=10000)

In [33]:
X_train = pad_sequences(X_train,padding='post',maxlen=50)
X_test = pad_sequences(X_test,padding='post',maxlen=50)

In [34]:
X_train.shape

(25000, 50)

In [37]:
model = Sequential()
model.add(Embedding(input_dim=10000, output_dim=2, input_length=50))
model.add(SimpleRNN(32,return_sequences=False))
model.add(Dense(1, activation='sigmoid'))

# Build the model explicitly
model.build(input_shape=(None, 50))

model.summary()

Model: "sequential_13"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ embedding_13 (Embedding)             │ (None, 50, 2)               │          20,000 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ simple_rnn_7 (SimpleRNN)             │ (None, 32)                  │           1,120 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_7 (Dense)                      │ (None, 1)                   │              33 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 21,153 (82.63 KB)

 Trainable params: 21,153 (82.63 KB)

 Non-trainable params: 0 (0.00 B)

In [38]:
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['acc'])
history = model.fit(X_train, y_train,epochs=5,validation_data=(X_test,y_test))

Epoch 1/5
782/782 ━━━━━━━━━━━━━━━━━━━━ 15s 17ms/step - acc: 0.5691 - loss: 0.6623 - val_acc: 0.7951 - val_loss: 0.4473
Epoch 2/5
782/782 ━━━━━━━━━━━━━━━━━━━━ 20s 16ms/step - acc: 0.8284 - loss: 0.3939 - val_acc: 0.8051 - val_loss: 0.4385
Epoch 3/5
782/782 ━━━━━━━━━━━━━━━━━━━━ 20s 16ms/step - acc: 0.8713 - loss: 0.3138 - val_acc: 0.8070 - val_loss: 0.4478
Epoch 4/5
782/782 ━━━━━━━━━━━━━━━━━━━━ 20s 16ms/step - acc: 0.8961 - loss: 0.2681 - val_acc: 0.7982 - val_loss: 0.4800
Epoch 5/5
782/782 ━━━━━━━━━━━━━━━━━━━━ 13s 16ms/step - acc: 0.9097 - loss: 0.2396 - val_acc: 0.7974 - val_loss: 0.4669
